### PR TITLE
Extensions support level changes

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@vkasala could you please review?

**Comment by svkcemk** [comment]
retest this please.

**Comment by ppalaga** [comment]
@svkcemk this is expected to fail because the changes resulting from the changes in camel-quarkus-product-source.json are not committed yet. I wanted to commit those only after @vkasala approves them.

**Comment by svkcemk** [comment]
Thanks @ppalaga make sense!

**Comment by vkasala** [comment]
Looks good! @ppalaga

**Comment by ppalaga** [comment]
Merging in spite of some test failures. Some have issues filed, some seem to be caused by Jenkins env.

**Pull request merged**
