### PR TITLE
fips fixes (mysql, kafka, jdbc, ...)

### PR DESCRIPTION
**Pull request by JiriOndrusek**
cherry-picked:
7d0eda5bc142e666aaefbee4b2be7a7dbe8c2cd1
f28d65979802af96be7af08293660616f728fa09
125ba5e3394397bd4eea2cca9f9e4af3c1dd6b5b
PR:  https://github.com/apache/camel-quarkus/pull/6209

cherry-picked 83661327711b8e8686c9d04e6cb8bee17e9043f8
PR: https://github.com/apache/camel-quarkus/pull/6213

cherry-picked 7a87bedde90f273a2e333c20a58e195778a2a3d7
PR: https://github.com/apache/camel-quarkus/pull/6267

cherry-picked 4ee3db2a86c49f34ee7c6f7e003501c4306dd689
PR: https://github.com/apache/camel-quarkus/pull/6272

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
The changes are for tests only. Therefore it could be easily decide whether the failure relates to the change from this PR.
The only one failure might be related - `kafka-ssl`
From the log error in that case:

```
 Container startup failed for image quay.io/strimzi-test-container/test-container:latest-kafka-3.2.1
 ...
 Could not create/start container
 ...
 Timed out waiting for log output matching '.*Recorded new controller, from now on will use broker.*'
  ```
  
I'll check locally whether there is a problem or not.

**Comment by JiriOndrusek** [comment]
Locally the test passes (both JVM and native).
From the log with the failure, I see that the certificates were generated successfully, therefore I don't think that the failure is related to this PR.

**Comment by jamesnetherton** [comment]
@zhfeng do you think this has any chance to mess up the prod platform? E.g we introduced a new test-support module etc. Not sure if it could cause issues.

**Comment by zhfeng** [comment]
Hmm, I think it should be OK. The prod platform still uses the original community tests. The new test-support module will not impact them.

**Comment by JiriOndrusek** [comment]
@zhfeng therefore it could be merged? QE would like to verify those FIPS fixes,

**Comment by zhfeng** [comment]
Yeah, go ahead please!

**Pull request merged**
