### PR TITLE
[ENTESB-16712] Fix #3169 to add S3 KMS encryption test

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.redhat.com/browse/ENTESB-16712

### CODE REVIEW

**Comment by zhfeng** [comment]
@ppalaga It needs to add camel-quarkus-kms in product artifacts because the S3 KMS test depends on it. Also it has to enable ```Service.KMS``` in localstack. Can you review these changes ?

**Comment by ppalaga** [comment]
@zhfeng I am afraid we cannot add KMS to productized extensions like this. It would require some agreement between ENG PM and QE, for which it is too late. If it was motivated only by wanting to satisfy the test dependencies, then there is an option to allow an exception like we do for other tests, e.g. here: https://github.com/jboss-fuse/camel-quarkus/blob/camel-quarkus-2.2.0-product/product/src/main/resources/camel-quarkus-product-source.json#L155 I am backporting more commits from upstream and try to address this in my branch.

**Comment by zhfeng** [comment]
Thanks @ppalaga and feel free to replace this one.

**Comment by ppalaga** [comment]
Superseded by https://github.com/jboss-fuse/camel-quarkus/pull/89

**Pull request closed without merging**
