### PR TITLE
 ENTESB-17306 Use links to product documentation in Quarkus metadata

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Review by squakez — APPROVED** [review]
Excellent!

**Comment by ppalaga** [comment]
@fbolton in the end the implementation is in a [single json file](https://github.com/jboss-fuse/camel-quarkus/pull/69/files#diff-2c9f4970c8c81fd26696fc68996b689e510cafa07d41de056e833a5b70294654) for all extensions. This file overrides parts of the upstream metadata by the product values. That's exactly what we need for the support levels and for guide URIs. Could you please throw a quick look at the file?

**Comment by fbolton** [comment]
@ppalaga Right, so we need to maintain the `.json` file, which contains explicit URLs for all the guides. This looks like a very flexible solution to me, since we can point the guides at any URL we need.

We probably don't have the definitive list of supported Camel Extensions (i.e. supported in the Camel Extensions for Quarkus 2.2 GA release) in our guide yet. I'll check with Gerry to make sure we update the guide to included all of the supported extensions (if necessary).

Anyway, the solution looks good to me. Thanks, Peter!

**Comment by ppalaga** [comment]
> Right, so we need to maintain the `.json` file

Yes, just note that `product/src/main/generated/camel-quarkus-product.json` is generated based on data from [product/src/main/resources/camel-quarkus-product-source.json](https://github.com/jboss-fuse/camel-quarkus/blob/camel-quarkus-2.2.0-product/product/src/main/resources/camel-quarkus-product-source.json). So strictly speaking we'll maintain `camel-quarkus-product-source.json` and the [script](https://github.com/jboss-fuse/camel-quarkus/blob/camel-quarkus-2.2.0-product/product/src/main/groovy/generate-camel-quarkus-product-json.groovy) that transforms it into `camel-quarkus-product.json`

**Comment by ppalaga** [comment]
Still no luck with pulling containers from Docker Hub. Merging in spite of that.

**Pull request merged**
