### PR TITLE
CEQ-5722 to add camel-quarkus-sap

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by zhfeng** [comment]
Hi @ppalaga,

I just creat `camel-quarkus-sap` extension. Some potenial issues:

- `camel-sap` component does not exist in `camel-catalog` on community side because it is a downstream only component in our `fuse-components` repo.
- The groupId is `org.fusesource` but not `org.apache.camel`
- It is `JVM only` support extension. I add it as the following json, is it right? And I also keep it in `extensions-jvm` directory.
```json
"camel-quarkus-sap": {
            "jvm": "supported",
            "native": "techPreview",
            "comment": "supported/tp since CEQ 3.0.0"
        },
```
- document url lik https://access.redhat.com/documentation/en-us/red_hat_integration/3.latest/html/camel_extensions_for_quarkus_reference/extensions-sap, is it OK?
- How to make it work with `cq:prod-init` to add this extension from previous prod branch?

**Comment by vkasala** [comment]
I believe the Native should be community supported.

**Comment by zhfeng** [comment]
@vkasala No, `camel-sap` is only in downstream repo. So we don't have any community version of it.

**Comment by zhfeng** [comment]
Or `community` supported means `NO Supported`?

**Comment by jamesnetherton** [comment]
> Or `community` supported means `NO Supported`?

Effectively, yes. As we currently lack any other way of flagging that an extension is supported in JVM only:

https://issues.redhat.com/browse/QUARKUS-3153

**Comment by jamesnetherton** [comment]
Superseded by #247.

**Pull request closed without merging**
