### PR TITLE
ENTESB-16717: Document the limitations for aws2-lambda getAlias and l…

### PR DESCRIPTION
**Pull request by aldettinger**
…istAliases operations

### CODE REVIEW

**Comment by ppalaga** [comment]
@aldettinger this limitation does not exist in the upstream?

**Comment by aldettinger** [comment]
@ppalaga  Actually, in 2.4.0-SNAPSHOT upstream only ListAliases has the limitation and it will corrected once we move to camel 3.13.0.

Are you suggesting to add the ListAliases limitation upstream and have a ticket to remove it once we adopt camel 3.13 ?

**Comment by ppalaga** [comment]
> @ppalaga Actually, in 2.4.0-SNAPSHOT upstream only ListAliases has the limitation and it will corrected once we move to camel 3.13.0.
> 
> Are you suggesting to add the ListAliases limitation upstream and have a ticket to remove it once we adopt camel 3.13 ?

I was just looking for some explanation why this commit is not present upstream :) I thought it might have to do with Camel 3.12.

For ListAliases, I do not have a strong opinion. If the fix is already present in Camel main branch, maybe we can let it be.

**Review by ppalaga — APPROVED** [review]

**Comment by aldettinger** [comment]
ok, many thanks for having a look and merging then :+1:

**Pull request merged**
