### PR TITLE
Upgrade to Quarkus CXF 2.2.6

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.redhat.com/browse/CEQ-7591

Note that Quarkus CXF upstream 2.2.6 uses CXf 4.0.3 that we do not want to productize at this point.
The PNC build config currently forces a `4.0.2.fuse-redhat-*` version anyway so the PNC builds of Quarkus CXF and CEQ should be as expected.
Testing in the midstream branch would be possible with a change like this: https://github.com/ppalaga/camel-quarkus/commit/3110f910271f1c3ae14fbe9000a5c24d3e0aa102
However having that in the midstream branch might in turn complicate the PNC builds so I am not making it a part of this PR.

### CODE REVIEW

**Comment by ppalaga** [comment]
I have added some minor fixes to make the CI happier. The js-dsl test will still fail due to https://issues.redhat.com/browse/CEQ-8281

**Comment by ppalaga** [comment]
Pulsar is still failing, because it takes the BOM from the Maven reactor, where bcprov-ext-jdk18on is managed at the prod version that is not available in indy. However the installed BOM is correct, containing the community version 1.74 of bcprov-ext-jdk18on. Let's ignore it for now.

**Comment by ppalaga** [comment]
Elastic search fails with `Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 3143 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked` and passes on my machine. Let's consider it caused by a slow CI node.

**Comment by ppalaga** [comment]
The last failing group is SJMS where the tests cannot connect due to `Connection refused` when posting to various  `/messaging/{queueName}` REST endpoints. They all pass for me locally. No idea what can be wrong on the CI.

**Review by jamesnetherton — APPROVED** [review]

**Pull request merged**
