### PR TITLE
[CEQ-6517] Extend the community camel-quarkus-catalog

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Review by jamesnetherton — APPROVED** [review]
Please create a follow-up Jira issue for CEQ 3.x to have this change added to the `cq-maven-plugin` `prodInitMojo`. Otherwise we are guaranteed to forget this again in future.

**Review by zbendhiba — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by ppalaga — APPROVED** [review]
Perfect @zhfeng!

**Comment by ppalaga** [comment]
> Please create a follow-up Jira issue for CEQ 3.x to have this change added to the cq-maven-plugin prodInitMojo. Otherwise we are guaranteed to forget this again in future.

I created the follow up https://issues.redhat.com/browse/CEQ-6528

**Comment by zhfeng** [comment]
@ppalaga The other question is why we includes `org.apache.camel:camel-catalog` here?

**Comment by ppalaga** [comment]
> why we includes org.apache.camel:camel-catalog here?

In upstream branches, the data from `org.apache.camel:camel-catalog` is used as a base for producing camel-quarkus-catalog. We basically just take it and transform it a bit.

For downstream branches, it is better to transform camel-quarkus-catalog from the associated upstream branch (so that all community extensions are kept untouched).

**Pull request merged**
