### PR TITLE
[docs] Document running the tests

### PR DESCRIPTION
**Pull request by llowinge**

### CODE REVIEW

**Comment by llowinge** [comment]
@vkasala Can you review please ?

**Comment by ppalaga** [comment]
@llowinge if this is supposed to be product related piece of docs, then I'd vote for having it somewhere under the [product folder](https://github.com/jboss-fuse/camel-quarkus/tree/camel-quarkus-2.7.1-product/product), so that it can be ported easily, once we rebase on top of a new upstream tag.

The [README](https://github.com/jboss-fuse/camel-quarkus/blob/camel-quarkus-2.7.1-product/product/README.adoc) in that folder is already quite long, so we may consider creating a separate testing.adoc document?

**Comment by llowinge** [comment]
@vkasala Is new testing.adoc placed under product folder acceptable for you ? We could point to it from the product README.

**Comment by llowinge** [comment]
@ppalaga Thank you for your input. I agree with you.

**Comment by vkasala** [comment]
@llowinge Yes, it's accepted.

**Comment by llowinge** [comment]
@ppalaga @vkasala Is it OK like that ?

**Comment by ppalaga** [comment]
Let me add a paragraph about how to run against the platform BOMs

**Comment by ppalaga** [comment]
Thanks @llowinge !

**Pull request merged**
