### PR TITLE
Camel Quarkus Core related backports

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.redhat.com/browse/ENTESB-16193

### CODE REVIEW

**Review by jamesnetherton — APPROVED** [review]

**Comment by ppalaga** [comment]
dd9b1fb: attempted to fix the failing tests

**Comment by ppalaga** [comment]
The CI failed on downloading some Camel artifact. Restarted

**Comment by ppalaga** [comment]
The CI passed finally. Would anybody like to review?

**Comment by ppalaga** [comment]
Ah, now I see that @jamesnetherton has approved an earlier version. Not much has changed, thus merging. Sorry for the noise.

**Pull request merged**
