### PR TITLE
Upstream backports

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by jamesnetherton** [comment]
To enable`openapi-java` as supported, does the BOM also need tweaking? I notice there's two versions in use for the CQ extensions.  `project.version` & `camel-quarkus-community.version`.

**Comment by ppalaga** [comment]
> To enable`openapi-java` as supported, does the BOM also need tweaking? I notice there's two versions in use for the CQ extensions. `project.version` & `camel-quarkus-community.version`.

Yes, of course! Thanks for catching this. I have not noticed at all that the BOM has this kind if changes. I thought it was magically done by PNC or the maven extension.

**Comment by ppalaga** [comment]
7a7617e: 
* Fixed the BOM (via `mvn org.l2x6.cq:cq-prod-maven-plugin:1.3.0:prod-excludes -N` )
* Added the docs fixes as agreed with @Gerry-Forde

**Review by jamesnetherton — APPROVED** [review]

**Comment by jamesnetherton** [comment]
@ppalaga Is this good to merge?

**Comment by ppalaga** [comment]
Hopefully, given that the CI is not reliable.

**Pull request merged**
