### PR TITLE
Increase FHIR container startup timeout to 5 minutes

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by ppalaga** [comment]
Is there any Jira to which we could associate this?

**Comment by jamesnetherton** [comment]
> Is there any Jira to which we could associate this?

No, unless @llowinge wants to create one.

**Review by ppalaga — APPROVED** [review]
Good to know whose wish is this :)

**Comment by jamesnetherton** [comment]
I created https://issues.redhat.com/browse/ENTESB-19207. And updated the commit comment.

**Pull request merged**
