### PR TITLE
Upgrade Camel to 3.14.2.redhat-00038

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Upgrade Camel to 3.14.2.redhat-00038

There is a problem caused by the productized bits in fhir. A lot of dependencies are productized, but not`ca.uhn.hapi.fhir:org.hl7.fhir.*` Therefore those dependencies brings `ca.uhn.hapi.fhir:hapi-fhir-base:4.1.0`, which is already brought as `ca.uhn.hapi.fhir:hapi-fhir-base:4.1.0.redhat-00002` by productized bits. I added several exclusions to overcome this. Once https://github.com/hapifhir/org.hl7.fhir.core is productized, we can remove them.

Replaces https://github.com/jboss-fuse/camel-quarkus/pull/163

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
I see that build failure is caused by some alignment errors. I'll try to simulate error localy and fx it. (I have 2 other PRs depending on this one)

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.l2x6.cq:cq-prod-maven-plugin:2.29.1:prod-excludes-check (check-excludes) on project camel-quarkus: Execution check-excludes of goal org.l2x6.cq:cq-prod-maven-plugin:2.29.1:prod-excludes-check failed: File [product/src/main/generated/transitive-dependencies-non-productized.txt] is not in sync with product/src/main/resources/camel-quarkus-product-source.json:



    Extra content at line 239:

  ["commons-lang:commons-lang"]



    Extra content at line 1751:

  ["org.slf4j:jcl-over-slf4j"]



    Extra content at line 1804:

  ["xpp3:xpp3"]
```

**Comment by jamesnetherton** [comment]
I think this is superseded by https://github.com/jboss-fuse/camel-quarkus/pull/167.

**Comment by JiriOndrusek** [comment]
Yes, you are right, thanks, I'll rebase my dependent PRs

**Comment by JiriOndrusek** [comment]
Superseded by https://github.com/jboss-fuse/camel-quarkus/pull/167

**Pull request closed without merging**
