### PR TITLE
Backports

### PR DESCRIPTION
**Pull request by ppalaga**
This contains https://github.com/jboss-fuse/camel-quarkus/pull/74 because I'd like to see both to pass separately.

### CODE REVIEW

**Review by jamesnetherton — COMMENTED** [review]
Small commit comment nitpick - We have `Upgrade to Quarkus 2.3.0.ER7` but of course it's 2.2.3 that we're focussed on. It had me worried for a second 🙂.

**Comment by ppalaga** [comment]
> Small commit comment nitpick - We have `Upgrade to Quarkus 2.3.0.ER7` but of course it's 2.2.3 that we're focussed on. It had me worried for a second slightly_smiling_face.

Of course, sorry for the confusion and thanks for noticing. Let me reword it before merging

**Comment by ppalaga** [comment]
3e01890: 
* Fixed the failing js DSL test: there is no productized `org.graalvm.js:js` so we have to use the community version.

**Comment by ppalaga** [comment]
I gave up to wait for the CI. Merging after running the JVM tests locally.

**Pull request merged**
